### ISSUE TITLE
System Information Leak：Internal

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [twitter/repo-scaffolding#7]
https://github.com/twitter/repo-scaffolding/blob/2586778ffdc133431f4cf648c13638ffed840772/add_license_headers.py#L538

An internal information leak occurs when system data or debugging information is sent to a local file, console, or screen via printing or logging.
It is recommended to use concise and ambiguous information to prompt the user

**Comment by OrkoHunter** [comment]
Hmm. I guess the concern is regarding `os.getcwd()`.

**Comment by QiAnXinCodeSafe** [comment]
yes

> 嗯 我想这里的担心是关于`os.getcwd()`。

**Comment by QiAnXinCodeSafe** [comment]
> 嗯 我想这里的担心是关于`os.getcwd()`。

yes

**Comment by willnorris** [comment]
because this is only printed the console of the person running the script, showing them their own current working directory is fine.
